dist: bionic 
language: python
python:
  - "2.7"
  - "pypy2"
  - "3.7"
  - "3.8"
  - "pypy3"
before_install:
  - pip install coverage
  - pip install codecov
install: pip install -r requirements.txt
script: coverage run -m unittest
after_success: codecov
